### ISSUE TITLE
Some users are unable to sign-up to the app.

### ISSUE THREAD

**Issue by jcampbell05** [Supmenow/sup-issues#1]
We have a report from one user who is unable to sign-up.

What we know:
- The user initially was unable to sign-in via Facebook (Learned via Mixpanel).
- The user has a firebase account and a profile on Mixpanel which indicates he eventually was able to login via Facebook.
- The user doesn't have a location.

Potential issue:
- Did the user struggle to authenticate with Digits ?

**Comment by jcampbell05** [comment]
Requested a screenshot of the issue from the user.. Actioned to @alexsup

**Comment by alexsup** [comment]
@jcampbell05 Haven't heard anymore about this.

Closing for now.
