### ISSUE TITLE
It isn't clear to some users why they should verify their number.

### ISSUE THREAD

**Issue by jcampbell05** [Supmenow/sup-issues#10]
Some user have sent feedback that they do not understand why they have to verify their number.

Possible Solutions:
- Information screen before verify screen 
- Only prompt them when going to the invite screen ?

**Comment by jcampbell05** [comment]
Seeking feedback from our design team.

**Comment by alexsup** [comment]
Agree. App = awful right now

**Comment by alexsup** [comment]
This is being fixed for version in version 4.
