### ISSUE TITLE
Flare list occasionally crashes

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-issues#13]
Scenario: Viewing created flare in flare list from Radar
  Given I create a flare
  When I click flares on the tab bar
  Then the app crashes

**Comment by jcampbell05** [comment]
@alexsup Could you create some steps to reproduce, I am not seeing this crash right now. I need more detail :)

**Comment by alexsup** [comment]
@jcampbell05 Steps above.

For clarity:

1. Create a flare.
2. Return to radar
3. Click on flares on the tab bar
4. Crash

**Comment by jcampbell05** [comment]
@alexsup when you created a flare what did you fill in / what options did you choose ?

**Comment by alexsup** [comment]
@jcampbell05, @roger-tan  I am getting this again.

Simply open the app, tap on flares, try to open a flare, the app crashes.

If I re-open and then tap on flares, the app crashes.

**Comment by jcampbell05** [comment]
A fix should be merged into dev.

**Comment by jcampbell05** [comment]
@alexsup  In a branch I get this but its only when you open and close it very quickly.

**Comment by alexsup** [comment]
OK, great. Let's fix it.

**Comment by jcampbell05** [comment]
@alexsup pushing some code to dev - in the next crashlytics release let me know if it's fixed for you and we can close.
