### ISSUE TITLE
Occasionally Radar appears empty

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-issues#14]
Occasionally, when opening the app, the radar is empty and stays empty.

Rich & Danny experienced this problem 11th/12th May.

**Comment by jcampbell05** [comment]
@alexsup if you can gather some more information about their situations and add it to this issue then this would be great 👍

**Comment by alexsup** [comment]
Ok, will do!

Thanks,

AB

*___________________________________*

*Alex⎥Head of Tech, Product and Things*

*alex@supmenow.com <alex@supmenow.com>⎥supmenow.com <http://supmenow.com/>*

*Sup*

*Runway East *

*10 Finsbury Square*

*London*

* EC2A 1AF *

**Comment by alexsup** [comment]
@jcampbell05 pushed to 4.2

**Comment by jcampbell05** [comment]
Potentially related to #41

**Comment by jcampbell05** [comment]
Seems to be due to slow loading times but new one should hopefully be quicker, closing in favour of #41
