### ISSUE TITLE
Flares aren't sorted into date order.

### ISSUE THREAD

**Issue by jcampbell05** [Supmenow/sup-issues#15]
We should sort flares by most recent first.

**Comment by roger-tan** [comment]
No, owner flares first and then Flare ordered by most recent

**Comment by alexsup** [comment]
For simplicity reasons, let's just make it chronological.

**Comment by jcampbell05** [comment]
@alexsup  Agreed, will tweak.

**Comment by jcampbell05** [comment]
This should be in dev now, will close once fix is confirmed
