### ISSUE TITLE
Flare action language is poorly formatted

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-issues#16]
There are still emojis in the middle of the action text rather than at the end.

DL is testing language evening of 12th.

**Comment by jcampbell05** [comment]
@alexsup let me know when DL has some.

**Comment by jcampbell05** [comment]
@alexsup was this updated ?

**Comment by roger-tan** [comment]
Will be.

**Comment by jcampbell05** [comment]
This should be in dev now, will close once fix is confirmed
