### ISSUE TITLE
Can't select now for a flare time

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-issues#18]
I have to select another time and then reselect now

**Comment by jcampbell05** [comment]
@alexsup Could you provide more detail ? The time picker should be now by default.

**Comment by alexsup** [comment]
@jcampbell05 The time picker is in 5 min intervals.

If the time is, say, 1023 the the initial pick is 1020 which is greyed out because it's in the past.

**Comment by jcampbell05** [comment]
@alexsup So you want to be able to pick in realtime not 5 minute slots ?

**Comment by alexsup** [comment]
@jcampbell05 don't have an opinion for now.

Needs to be better in the future.

Happy that #19 will make this usable for now.

**Comment by jcampbell05** [comment]
@alexsup  I believe this was by design so you should discuss this with Pierre.
