### ISSUE TITLE
I can't close flare time

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-issues#19]
Seems really odd that I can't do this

**Comment by jcampbell05** [comment]
@alexsup  You can if you tap outside but we should add a done button the user can visibly see.

**Comment by alexsup** [comment]
@jcampbell05 I can't close the time by clicking outside the box

**Comment by jcampbell05** [comment]
I'll see if I can reproduce.

**Comment by alexsup** [comment]
@roger-tan @jcampbell05 

Let's take time out of the flare flow.

Can we just remove it?

It's not in milestone 4.5.

Save time.

**Comment by alexsup** [comment]
Changed label to wontfix

**Comment by jcampbell05** [comment]
That makes sense we will just save the created at and let the flare expire after 30 minutes
