### ISSUE TITLE
The app is sending text invites to duplicate contacts.

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-issues#2]
According to Plivo, the app has sent 5,567 messages since the launch last week, which seems like alot.

We should verify we are sending the correct amount.

**Comment by jcampbell05** [comment]
@alexsup could you provide the information from Plivio of what was sent.

**Comment by jcampbell05** [comment]
@alexsup potentially this is due to duplicate contacts in a user's contacts book. @roger-tan  is working on filtering out duplicate contacts to resolve this.

**Comment by jcampbell05** [comment]
@alexsup we have also just merged in a fix to filter out non-mobile numbers.

**Comment by alexsup** [comment]
@roger-tan Can we remove this as a bug?

**Comment by jcampbell05** [comment]
@alexsup Fixed in 4.0
