### ISSUE TITLE
Facebook crashes when authenticating for sharing for flare

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-issues#22]
To replicate, go through the authentication flow

**Comment by jcampbell05** [comment]
@alexsup this is when you press the facebook button when creating a flare right ?

**Comment by alexsup** [comment]
Yes, it crashed when returning from Facebook Auth.

**Comment by alexsup** [comment]
@jcampbell05 @roger-tan 

Please removed from 4.0 and hide from interface.

Added to 4.5.

**Comment by jcampbell05** [comment]
Okay will hide from interface. When is 4.5 I'll update the milestone ?

**Comment by alexsup** [comment]
@jcampbell05 Milestone updated.

@roger-tan Has already updated.

Please do PRs :)

**Comment by jcampbell05** [comment]
@ab on them :)

**Comment by jcampbell05** [comment]
This no longer a feature, closing.
