### ISSUE TITLE
Facebook share to profile needs authorised

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-issues#23]
Sup needs to request permission from Facebook to request write permissions.

**Comment by jcampbell05** [comment]
@alexsup we should request permissions, could you explain the issue more clearly perhaps provide some steps to reproduce.

**Comment by alexsup** [comment]
It's todo with Facebook management, we need to apply for it.

**Comment by jcampbell05** [comment]
Okay, this is more of a task than a issue. I'll close for now and move this to our release checklist.
