### ISSUE TITLE
I can't see Flares on the Radar

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-issues#25]

**Comment by jcampbell05** [comment]
@alexsup  I'm not sure if we should even implement this, at least for this sprint:
- The next design seems to drop this in favour of just users on the Radar.
- This would make the radar even more complex (already getting bugs).
- There are a lot of questions to still answer in spikes for this.

**Comment by alexsup** [comment]
@jcampbell05 Check the documentation of Gherkin stories and user flow.

– Flares on radar that I've been invited to.

BUT....

Let's push this to v5.

**Comment by jcampbell05** [comment]
@alexsup  Haven't had a chance to check them out yet, but will look once v4 is pushed.

Agreed with v5, closing for now since this is no longer a bug.
