### ISSUE TITLE
If I click on a flare in the flare list, it doesn't show me the flare pop up.

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-issues#26]

**Comment by roger-tan** [comment]
Which Flare Popup?

**Comment by jcampbell05** [comment]
@roger-tan The Flare Preview. It should show up when tapping a flare on the flare list.

**Comment by alexsup** [comment]
The one with the cat gif :)

**Comment by jcampbell05** [comment]
@alexsup  should be fixed in the last crashlytics build, let me know and we can close this issue

**Comment by alexsup** [comment]
Good job.

This is closed!
