### ISSUE TITLE
I am unable to exit a flare preview after returning from chat.

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-issues#30]
Given I am on flare preview
When I click I'm coming
And I go to chat
And I return to the flare preview
Then There is no way to exit flare preview

**Comment by jcampbell05** [comment]
@alexsup  do you mean you return to the flare preview ?

**Comment by roger-tan** [comment]
No close button?

**Comment by jcampbell05** [comment]
@roger-tan yes this is the screenshot

![image](https://cloud.githubusercontent.com/assets/1484989/15248054/f90aabb8-190f-11e6-933a-0f7c01c88d4c.png)

**Comment by roger-tan** [comment]
Ok, I have an idea when the button the navigation bar is not visible after un chat.

**Comment by jcampbell05** [comment]
Awesome is that because we hide it ?

**Comment by roger-tan** [comment]
Because the Chat Message does!

**Comment by jcampbell05** [comment]
Ah it shouldn't hide the navigation bar on view disappear 😀 it should only change its appearance on appear

**Comment by jcampbell05** [comment]
This should be in dev now, will close once fix is confirmed
