### ISSUE TITLE
Update language inline with DL's requirements

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-issues#31]
Ask Danny for requirements

**Comment by jcampbell05** [comment]
@alexsup can you add all of the other tasks into the description of this task as a check list (Look at the github markdown to see how a checklist is done)

**Comment by alexsup** [comment]
Sure.

**Comment by alexsup** [comment]
Moved to 4.5

**Comment by alexsup** [comment]
@jcampbell05 Do we need to bump this to 4.6?

**Comment by jcampbell05** [comment]
This is an umbrella tasks, it's hard to say when it should be as it doesn't reference all the other tasks that this task represents.

I'll close this one and just focus on the other tasks.
