### ISSUE TITLE
Pre-defined text from flare doesn't trigger send state

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-issues#32]
Given I'm on flare preview
When I click on I'm Coming
Then it profiles the text
And it shows the sup button
And not the send button

**Comment by jcampbell05** [comment]
Is the text sent or just pre-filled ?

**Comment by alexsup** [comment]
It is pre-filled but because I haven't done any key ups/downs then the sup button doesn't change to a send button.

**Comment by jcampbell05** [comment]
Okay makes sense, I'll update it so the visibility of the send button is binded to the text value.

**Comment by jcampbell05** [comment]
Merged into dev, will close once fix is confirmed.
