### ISSUE TITLE
Language: Loading radar

### ISSUE THREAD

**Issue by Dannylowney** [Supmenow/sup-issues#33]
**Location:** Radar view when loading friends
**Current copy:** Hold on a tick.... We're looking for your friends...
**Replace with:** Hold up. We're just looking for your nearby friends...

**Comment by alexsup** [comment]
@roger-tan Here is a text change.
Thanks @Dannylowney.

**Comment by jcampbell05** [comment]
@roger-tan did we do this ?

**Comment by roger-tan** [comment]
Not yet!

**Comment by alexsup** [comment]
@roger-tan  @jcampbell05 are we planning this for 4.5?

**Comment by jcampbell05** [comment]
@alexsup Sure
