### ISSUE TITLE
Language: Invite friends to Sup page

### ISSUE THREAD

**Issue by Dannylowney** [Supmenow/sup-issues#34]
**Location:** Settings>Friends on Sup>Add Friends to Radar>
**Current copy:** Tap below to share SUP with friends you want to see more
**Replace with:** Get the squad to join Sup so you can start hanging out more.

**Current copy:** Share with friends 
**Replace with:** Share

**Comment by alexsup** [comment]
@roger-tan @jcampbell05 is this in?

**Comment by jcampbell05** [comment]
@alexsup  Not yet.

**Comment by jcampbell05** [comment]
@alexsup  does this old invite screen even make sense to keep? What about just pushing to the new Text based system ?
