### ISSUE TITLE
Language: Twitter invite

### ISSUE THREAD

**Issue by Dannylowney** [Supmenow/sup-issues#35]
Location: Twitter invite
Current: #FOMO sucks...
Replace with: 👋🎈Sup me! [download link]
Priority: LOW

**Comment by jcampbell05** [comment]
@alexsup So what should the download link be ? Unique referral link or do we have a branch link we can use (We should have one already).

**Comment by Dannylowney** [comment]
As it is: bnc.lt/twitsup  <https://t.co/AC8USkDXkY>

On Fri, May 13, 2016 at 1:33 PM, James Campbell <notifications@github.com>
wrote:

> @alexsup <https://github.com/alexsup> So what should the download link be
> ? Unique referral link or do we have a branch link we can use (We should
> have one already).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Supmenow/sup-issues/issues/35#issuecomment-219030255>
>



-- 
Growth ⛏
danny@supmenow.com
+44 7973 954 846

**Comment by alexsup** [comment]
@jcampbell05 @Dannylowney Moved to v4.5

**Comment by Dannylowney** [comment]
Cool :)

On Fri, May 13, 2016 at 1:36 PM, Alex Barton <notifications@github.com>
wrote:

> @jcampbell05 <https://github.com/jcampbell05> @Dannylowney
> <https://github.com/Dannylowney> Moved to v4.5
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Supmenow/sup-issues/issues/35#issuecomment-219030933>
>



-- 
Growth ⛏
danny@supmenow.com
+44 7973 954 846

**Comment by alexsup** [comment]
@jcampbell05 @roger-tan update please

**Comment by jcampbell05** [comment]
@alexsup Not yet.
