### ISSUE TITLE
Language: Whatsapp/SMS invite

### ISSUE THREAD

**Issue by Dannylowney** [Supmenow/sup-issues#36]
Location: Whatsapp/SMS invite
Current: Download the hottest...
Replace with: Hey! 👋 I've personally selected you to join me on the Sup app 😉. It makes it waaaayyyy easier for us to meet up by letting you know when I'm nearby. Download the app and if you see that I'm in your area, drop me a message so we can hang out! supme.co/downloadsuplink

Priority: LOW

**Comment by alexsup** [comment]
@Dannylowney You say this is a low priority. 

Is this for the 26/5 release or the one after?

**Comment by Dannylowney** [comment]
This was in reply to you asking if there were any language changes to be
made in the *current* product (that James pushed to Crashlytics last night)

Ideally for the 26/5 release, yes.

On Fri, May 13, 2016 at 1:21 PM, Alex Barton <notifications@github.com>
wrote:

> @Dannylowney <https://github.com/Dannylowney> You say this is a low
> priority.
>
> Is this for the 26/5 release or the one after?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Supmenow/sup-issues/issues/36#issuecomment-219028009>
>



-- 
Growth ⛏
danny@supmenow.com
+44 7973 954 846

**Comment by jcampbell05** [comment]
Is this for the invite where you tap people and it sends or this is where we share the app ?

**Comment by jcampbell05** [comment]
or both.

**Comment by jcampbell05** [comment]
@Dannylowney can you make this fit inside a tweet, this is expensive.

**Comment by alexsup** [comment]
@Dannylowney Where is this text?

**Comment by Dannylowney** [comment]
The Master Plan > Message > D148 and D150

On Thu, May 26, 2016 at 4:21 PM, Alex Barton <notifications@github.com>
wrote:

> @Dannylowney <https://github.com/Dannylowney> Where is this text?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Supmenow/sup-issues/issues/36#issuecomment-221903130>
>



-- 
Growth ⛏
danny@supmenow.com
+44 7973 954 846

**Comment by jcampbell05** [comment]
Updated in https://github.com/Supmenow/Sup-iOS/pull/999
