### ISSUE TITLE
The create an account on Digits confuses users

### ISSUE THREAD

**Issue by jcampbell05** [Supmenow/sup-issues#37]
Users upon seeing create an account on the Digits verification screen are confused and believe they are making a new account.

**Comment by alexsup** [comment]
@jcampbell05 Can you clarify? A new account after Facebook login?

**Comment by jcampbell05** [comment]
@alexsup So when a user logs in via Facebook, they get a digits screen.

The screen after they enter their phone number has a "create account" button which is confusing if it's a returning user. 

It should ideally say something like "Login" or something.

**Comment by alexsup** [comment]
@jcampbell05 Is this something we can change?

**Comment by jcampbell05** [comment]
@alexsup I am not sure, we should looks to it for 4.5

**Comment by alexsup** [comment]
@jcampbell05 Closing. And moving to Pierre / Danny discusion
