### ISSUE TITLE
Does mixpanel update in the background?

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-issues#38]
I can't see any evidence that Mixpanel "Last Location Updated" is updated when:

1.  The app is in the background
2.  The app is terminated

Please confirm.

**Comment by jcampbell05** [comment]
@alexsup  I've tweeted them to clarify their upload policy. Other analytics I've been able to find information on specify that they batch events up and some even only do it on app open (not background).

https://twitter.com/jcampbell_05/status/732151800653090816

**Comment by alexsup** [comment]
@jcampbell05 Any update?

**Comment by jcampbell05** [comment]
https://twitter.com/jcampbell_05/status/732151800653090816
