### ISSUE TITLE
It takes a long time to load the contacts list.

### ISSUE THREAD

**Issue by jcampbell05** [Supmenow/sup-issues#39]
We have feedback that the contacts screen takes about 7 seconds to load. 
https://www.buglife.com/apps/sup/reports/26

**Comment by alexsup** [comment]
@jcampbell05 Likely scale issue due to RP size of phone book.

However, I've experience also.

Not for 4.0.

Please ask Pierre for loading screen for 4.5.

**Comment by alexsup** [comment]
A potential push to 4.6

**Comment by jcampbell05** [comment]
Pushed to next release

**Comment by jcampbell05** [comment]
@alexsup  Doesn't help with the loading times but we incrementally load the list now, so the user will see the first page before it's fully loaded.

https://github.com/Supmenow/Sup-iOS/pull/1003
