### ISSUE TITLE
Message excerpt is wrongly attributed.

### ISSUE THREAD

**Issue by jcampbell05** [Supmenow/sup-issues#4]
When a message excerpt is shown in the list of chats then it is shown as being from the wrong user.

i.e if a message is from another user it shows as being sent from the user looking at the list rather than the other user.

In the screenshot below the message was actually sent by James Campbell

![13148428_10156825191250693_250877792_o](https://cloud.githubusercontent.com/assets/1484989/14984559/3959a37c-113b-11e6-8577-8718fd00ffab.jpg)

**Comment by jcampbell05** [comment]
@alexsup is this a wont fix since we are removing chat ?

**Comment by alexsup** [comment]
Yep. Don't close but put wontfix.

**Comment by jcampbell05** [comment]
@alexsup shouldn't we close if it's a wont fix ? Otherwise it gets messy

**Comment by alexsup** [comment]
Sure
