### ISSUE TITLE
Flare response message can't be sent

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-issues#44]
Given I am on the flare list
When I click on flare
And click on "I'm coming"
Then The message is squashed
And I can't send the message

**Comment by jcampbell05** [comment]
@alexsup  these are two issues since the title is about not being able to send a message this issue will henceforth be about the send button being disabled.

**Comment by jcampbell05** [comment]
https://github.com/Supmenow/Sup-iOS/pull/935 this fixed the disabled I'm coming button
