### ISSUE TITLE
Block user from Sup doesn't seem to work

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-issues#46]
Given I am on the flare list
When I slide left 
And click block
Then the flare stays there
And I can still get flares from that user
And I can't see them in my blocked list

**Comment by alexsup** [comment]
@jcampbell05 Technically this should be in for 4.0.

Pushed to 4.5

**Comment by jcampbell05** [comment]
@alexsup  this should work in the latest code on `dev`
