### ISSUE TITLE
flareQueue doesn't care about g

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-issues#47]
@jcampbell05 In general, each event in a queue should be actionable. If not it shouldn't be there.

The flaresQueue is only interested in new flare creation only, not updates.

For simplicity, please remove any updates to queue items (g).

Please add location to the flare creation event.

This will allow notifications to work.

To clarify: One flare = One event (not three 👍 )

**Comment by jcampbell05** [comment]
@alexsup moving the location data into the multiwrites rather than using Geofire. In future we should move away from Geofire.

**Comment by jcampbell05** [comment]
Fixed in https://github.com/Supmenow/Sup-iOS/pull/931

**Comment by alexsup** [comment]
Thanks @jcampbell05
