### ISSUE TITLE
Flare error language is incorrect

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-issues#48]
- User didn't pick an activity: Hold up! | Please select an activity | OK
- User didn't pick a location: Hold up! | Please select a location | OK
- There was an issue making the flare (i.e poor internet): Cannot Send Flare | Please check your internet connection and try again. | OK
- We couldn't access the camera or it isn't avaliable.

**Comment by jcampbell05** [comment]
@alexsup  Can we push `User didn't pick either` to another release, it requires a logic change.

**Comment by jcampbell05** [comment]
@alexsup  potentially the same for settings as well :)

**Comment by alexsup** [comment]
@jcampbell05 Anything that isn't a simple text change can go.

Will put in Jira

**Comment by alexsup** [comment]
@jcampbell05 In Jira and updated
