### ISSUE TITLE
Some messages show "message loading..." after a very long time.

### ISSUE THREAD

**Issue by jcampbell05** [Supmenow/sup-issues#5]
In the screenshot below one message is still loading even after all the others have loaded.

![13148428_10156825191250693_250877792_o](https://cloud.githubusercontent.com/assets/1484989/14984611/7fbda584-113b-11e6-9e44-a96ab7b73118.jpg)

**Comment by jcampbell05** [comment]
@alexsup is this a wont fix since we are removing chat ?

**Comment by alexsup** [comment]
@jcampbell05 Technically yes.

And the Just Now bug.

We could keep chat but remove chat list. We will do this in 4.5.

**Comment by jcampbell05** [comment]
@alexsup that makes sense most bugs are in the list
