### ISSUE TITLE
Crazy delete behaviour

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-issues#53]
Given I am on the flare list
When I swipe left and delete
Then the screen glitches
And random other flares are auto swiped to the left

**Comment by jcampbell05** [comment]
@alexsup Auto-swiped, could you record this behviour so I can get a better idea of what you mean.

**Comment by alexsup** [comment]
@jcampbell05 Will do after 4.0 is released

**Comment by alexsup** [comment]
@jcampbell05 Pushed to 4.2

**Comment by jcampbell05** [comment]
Updated animation https://github.com/Supmenow/Sup-iOS/pull/1002
