### ISSUE TITLE
Flare preview never loads from any flare notifications

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-issues#58]
Given I receive a flare notification
When I swipe right 
And enter the app
Then the flare details never load

Ever.

**Comment by alexsup** [comment]
@jcampbell05 What further information do you need?

**Comment by jcampbell05** [comment]
@alexsup a reproducible case

**Comment by alexsup** [comment]
@jcampbell05 Ok. Please let me know when you have time to reproduce.

**Comment by alexsup** [comment]
@jcampbell05 Moved to 4.2
