### ISSUE TITLE
Some chats have the wrong message excerpt

### ISSUE THREAD

**Issue by jcampbell05** [Supmenow/sup-issues#6]
In the screenshot below the chat for Joaquim is showing the message for the chat with James, and the one for Linda is the chat for Pierre.

![13148428_10156825191250693_250877792_o](https://cloud.githubusercontent.com/assets/1484989/14984611/7fbda584-113b-11e6-9e44-a96ab7b73118.jpg)

**Comment by jcampbell05** [comment]
@alexsup is this a wont fix since we are removing chat ?

**Comment by alexsup** [comment]
Yep. Keep open.

**Comment by jcampbell05** [comment]
@alexsup isn't a wont fix a close?
