### ISSUE TITLE
Location updates don't happen unless I open the app

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-issues#62]
I never receive nearby notifications unless I open the app.

Details:

1. The server is known to work 100% when firebase updates it's location
2. Therefore, firebase isn't being updated unless I open the app.

This leads me to believe that significant updates aren't working.

**Comment by jcampbell05** [comment]
I can confirm Significant Updates are working, so maybe firebase isn't updated. This is probably related to https://github.com/Supmenow/sup-issues/issues/41

**Comment by alexsup** [comment]
I thought that might be the case but didn't want to presume.

A useful test is I should instantly get notifications when I come out of the tube in the morning.

**Comment by jcampbell05** [comment]
@alexsup  I better test than that would be:

Given that I am on a good network i.e Wi-Fi, I have just connected after being on airplane mode and the app is terminated
then the app should get a background location update, launch in the background and eventually update firebase with my location.

**Comment by alexsup** [comment]
@jcampbell05 I don't trust this test.

**Comment by jcampbell05** [comment]
@alexsup Well there are a few issues with that situation:
- When developing it I can't go in and out of a tube :P
- What if you came out of the tube and it wasn't instant due to your phone taking a while to get enough speed to transfer data ?
- Log Entries would be a better refection of this as we can track how many significant updates we had followed by a successful firebase write.

**Comment by alexsup** [comment]
@jcampbell05 It's more to do with knowing that the app works in real life like it used to.

To be clear, I expect the behaviour to return to the way it was.

How we get there via tests is up to you.

**Comment by jcampbell05** [comment]
@alexsup The best option I think would to hopefully have some sort of Health Metric we can use to monitor how many background updates are correctly being updated.

**Comment by alexsup** [comment]
@jcampbell05 Sure. Let's focus on this sprint then address issues :)

**Comment by alexsup** [comment]
@jcampbell05 pushed to 4.2

**Comment by jcampbell05** [comment]
Should be fix in latest dev.
