### ISSUE TITLE
Change text notifications for Flares

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-issues#63]
SMS Invite non-user to see Flare screen:

👋 I'm [activity] in [location]. Come join me! Check my Sup page for the details [link to flare] 🎈

**Comment by jcampbell05** [comment]
@alexsup  This going to be a API thing now ?

**Comment by alexsup** [comment]
@Dannylowney The problem with above is that the term that comes from the app is "Let's get lunch".

It doesn't really fit with above

**Comment by alexsup** [comment]
@jcampbell05 Yes. It's based off the flare listener :)

See the model for info.

**Comment by alexsup** [comment]
@jcampbell05

**Comment by alexsup** [comment]
@jcampbell05 Ah, I understand.

Will adjust for back end.

**Comment by Dannylowney** [comment]
**SMS Invite non-user to see Flare screen:**

[Fname L]: 👋 Let's [activity] at [location]. I'm here now - come along! Check my Sup page for the details [link to flare] 🎈

**Comment by alexsup** [comment]
Done :)
