### ISSUE TITLE
It isn't clear to the user when they are hidden or what that means.

### ISSUE THREAD

**Issue by jcampbell05** [Supmenow/sup-issues#7]
In the screenshot below the user was confused as to why they couldn't see their friends or anyone on the radar whilst being hidden (A behavior change / potential bug in the latest release).

![13120452_10156825205485693_2098762690_o](https://cloud.githubusercontent.com/assets/1484989/14984679/d264c6be-113b-11e6-955c-8f93acf58f34.jpg)

Questions to answer:

- Should we show people on the radar whilst hidden
- How do we educate people what being "hidden" means.

**Comment by jcampbell05** [comment]
Our design team are actioning a new design which will hopefully make the hidden state more clear to the user.

**Comment by jcampbell05** [comment]
So the design team are working on improving the state for this screen but in the next release we will have a improved hide icon to make this more obvious.

**Comment by alexsup** [comment]
@jcampbell05 Added defect label. Being looked at in v4

**Comment by jcampbell05** [comment]
@alexsup  we have a fix going into v4.

**Comment by alexsup** [comment]
@jcampbell05 Great!

Thanks J :)

Club Mate for you!

**Comment by jcampbell05** [comment]
@alexsup  okay, get me some tommorrow. Once my two PRs are merge we can validate this.

**Comment by jcampbell05** [comment]
Should be in latest dev.
