### ISSUE TITLE
Invitation text too long.

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-issues#77]
The invitation text is too long when inviting a user to join the app.

It's costing us a lot of money 👎

**Comment by jcampbell05** [comment]
@alexsup  do we have updated text ?

**Comment by alexsup** [comment]
@jcampbell05 It's in the master sheet :)

https://docs.google.com/spreadsheets/d/1WC9Z0D0wCqKzFOmzpzts_ZYCn9RcyLvTd5xCTHd7hjM/edit#gid=2108648799

If in doubt speak to Danny

**Comment by jcampbell05** [comment]
Will update :D

**Comment by jcampbell05** [comment]
Should be fixed in https://github.com/Supmenow/Sup-iOS/pull/995
