### ISSUE TITLE
User shouldn't be able to send invites to non-mobile numbers

### ISSUE THREAD

**Issue by jcampbell05** [Supmenow/sup-issues#9]
Currently when a user sends a text invite it goes to all numbers, we should restrict it to mobiles only.

**Comment by alexsup** [comment]
@jcampbell05 @roger-tan Where are we with this? 

Has this been committed?

**Comment by roger-tan** [comment]
It has been committed!

**Comment by jcampbell05** [comment]
@alexsup we have implemented a filter in the next release so we just need to validate the fix.

**Comment by jcampbell05** [comment]
@alexsup once we confirm the fix we can close this issue.

**Comment by alexsup** [comment]
@roger-tan @jcampbell05 Can we close this?

**Comment by jcampbell05** [comment]
@alexsup does the latest crashlytics only show mobile ? if yes, then we can close it.

**Comment by alexsup** [comment]
@jcampbell05 If you mean in the add friends to radar section, then yes!

**Comment by roger-tan** [comment]
@alexsup We should close this when we release the app.

**Comment by jcampbell05** [comment]
We should ideally close these once they are in dev so we can easily see whats been fixed.

@alexsup  In that case I'll close.
